### ISSUE TITLE
Firebase'te depolanacak veriler

### ISSUE THREAD

**Issue by ssukru** [pauieeecs/logicl#10]
Ekteki görselde kendimce bütün verileri türlerini yazmaya çalıştım. Eksikleri var mıdır, neleri iyileştirebiliriz?
Başlıklar: 

- User
- Team
- Idea
- Comment
- Team apply

![data](https://user-images.githubusercontent.com/53811483/108167751-37cfb100-7107-11eb-8bb1-4ece9df93caa.png)

**Comment by yunusemredilber** [comment]
Öncelikle elinize sağlık. Gördüğüm en büyük sorun user ID'leri ile ilgili. User tablosunda id alanı gerekiyor. Bu şekilde diğer tablolara da referans edebiliriz. Örneğin idea tablosunda arthourFullName diye tekrardan bir veri turuyoruz. Oysaki bu ve birçok veri user tablosunda mevcut. Onun yerine authourID diye bir alan tutup bunu user tablosu ile ilişkilendiremez miydik ? Gördüğüm bir diğer sorun team ile user'ları nasıl ilişkilendireceğimiz. Bu tarz bir ilişkilendirme (many-to-many) için arada bir join table olması gerekiyor.
Aşağıdaki gibi bir tablo oluşturabilirsiniz (applier tablosunu göz ardı ederek belirtiyorum):
|  	| users_teams 	|
|-	|-	|
| user_id 	| foreign key 	|
| team_id 	| foreign key 	|

Bu tabloya eklemeler yaparak katılım fonksiyonunu sağlamış olursunuz diye düşünüyorum. Şu anki yapıda user tablosunda tuttuğunuz için kullanıclıar sadece bir adet takıma katılabilir. Ayrıca yine user tablosunda teamName yerine teamID tutmak daha sağlıklı olur. Yoksa bir takım adını değiştirdiğinde çok fazla problem oluşacaktır. İlişkili tüm verileri **name**leri yerine **id**leri ile ilişkilendirmelisiniz.

Yeni halini tamamlayıp atarsanız yine bu issue altından tartışmaya devam edebiliriz.

İyi çalışmalar :)

**Comment by ssukru** [comment]
firestore nosql olduğu için böyle alakalı yerlere referans vermek yerine verileri de-normalize etmek daha doğru değil mi? kullanıcı bilgilerini çekmek için de ayrı okuma yapmamız gerekecek. bu şekilde query zamanı uzayacak ve fazla okuma yapmış olucaz. yani relationship olması kesinlikle daha iyi fakat bu durumda 1 döküman okumak yerine 3-4 döküman okuyacağız. alakalı updateler yapıldığında da mecburen ilişkili dökümanları update edicez. kullanıcı bilgilerinin nadir değiştiğini varsayarsak, güzel bi trade-off olur bence.

**Comment by yunusemredilber** [comment]
Nosql olsa bile bu şekilde tutmak verileri bir süre sonra kararsızlaştırır diye düşünüyorum. No sql'in ilişkilere çok hızlı dönen mekanizmaları var zaten. İleride güncellenmiyeceğinden emin olduğun verileri düz basabilirsin. Ama burda birbiriyle net ilişkili ve canlı bir mekanizma var. Son kararı size bırakıyorum ama bana bu haliyle çok sağlıklı gelmiyor. Okumanın mailyeti yazmaya göre oldukça azdır. Burada yazmaya bel bağlamak özellikle çok veri olduğunda kafa ağrıtır diye düşünüyorum. Veritabanın temel mantığı tekrar eden bilgileri azaltmaktır. Bu yapıda aynı verilerin her modelde tutulması db mantığına aykırı bence direkt.

**Comment by ssukru** [comment]
ben de todd kerpelman reyizin yalancısıyım 😄 ufak bi hesaplama yapayım. onun sonuçlarını da buradan sunayım, ona göre bi karar veririz. kesinlikle böyle organize etmesi zor.

**Comment by yunusemredilber** [comment]
Bu arada ilişkili tablolardan okumayı direkt query seviyesinde yapmalısınız. Join işlerini client'da yaparsanız dediğin gibi gereksiz bir mailiyet olur. Belki orası kafa karıştırmıştır. Tek bir istek attığınızda verileri birleştirme işini sql yapıp size tüm sonucu tek response'da dönmesi gerekiyor.

**Comment by ssukru** [comment]
anladım. kafamda bazı yerler için real-time listenerlar kullanmak vardı, o zaman onları da iptal ediyorum. API ile her şeyi bütün halde geri döndürürüz dediğin gibi

**Comment by yunusemredilber** [comment]
Bu dediğim işlemler veritabanının doğası gereği olması gerek şeyler zaten. Bu kadar ilişkili tablo varken ilişkisel veritabanı modelinde ilerlememek uygun olmayan yöntemi kullanmak olur fikrimce. Dediğim olayı realtime listenerlar ile yapılması gerekiyor. Şöyle bir yazı buldum belki faydalı olur: [https://medium.com/@alfianlosari/firebase-realtime-database-many-to-many-relationship-schema-4155d9647f0f](https://medium.com/@alfianlosari/firebase-realtime-database-many-to-many-relationship-schema-4155d9647f0f)

**Comment by ssukru** [comment]
hocam firestore yerine rtdb mi kullanıyoruz o zaman? ben tüm şeyleri firestore üstüne düşünmüştüm. rtdb nasıl çalışır pek bilmiyorum, biraz araştırayım ne olduğunu.

**Comment by yunusemredilber** [comment]
O zaman kararı size bırakıyorum. Bildiğiniz teknoloji üzerinden istediğiniz gibi ilerlemeniz daha sağlıklı olacak gibi. Firebase konusunda siz kadar deneyimli değilim. Ben sadece farklı bir bakış açı sunmak ve endişelerimi dile getirmek istedim. Verilerin kararlılığını sağlamak için de bir öneri sundum :)

**Comment by ssukru** [comment]
anlıyorum anlıyorum. issue açmamın sebebi senin görüşlerini de alabilmekti zaten :D ben rtdb ye de bakayım, belki bu problemi daha iyi çözüyodur. tekrar görüşlerimi toparlayıp bu issue altına yazıcam, hemfikir ilerleriz böylece
