### ISSUE TITLE
Uygulama Dili

### ISSUE THREAD

**Issue by yunusemredilber** [pauieeecs/logicl#26]
Uygulamayı ingilizce veya en azından multi-language  yapsak daha iyi değil miydi ?

**Comment by ssukru** [comment]
şu an ingilizce versiyonu ile ilgilenemeyeceğimiz için kapatıyorum bu issue'yu

tatlı bi şekilde kapamış olalım:

github kullanan kızlar nasıl hapşurur?
issue diye
