### ISSUE TITLE
[Bug] An unexpected error has occured hatası

### ISSUE THREAD

**Issue by yunusemredilber** [pauieeecs/logicl#27]
Şu an [develop ortamında](https://logicl-dev.netlify.app/) aşağıdaki hatayı alıyorum:

<img width="442" alt="Screen Shot 2021-02-27 at 15 06 07" src="https://user-images.githubusercontent.com/46731483/109386677-573bba80-790d-11eb-80c0-c8ab6f9468bb.png">

Konsola sonsuz bir döngü içerisinde şu hatayı basıyor. Bir hata olsa bile bu şekilde olmaması gerekiyor bence. Muhtemelen daha büyük bir dert var.

<img width="901" alt="Screen Shot 2021-02-27 at 15 06 47" src="https://user-images.githubusercontent.com/46731483/109386687-6d497b00-790d-11eb-94e4-e2ecb776bb85.png">

**Comment by ssukru** [comment]
env dosyasından çağırıyordum configdeki değerleri. arkadaşlara .env.local dosyalarını dağıttım fakat webde yayında olan halinde bunları ayarlamadığımız için çalışmıyor olabilir :D

**Comment by yunusemredilber** [comment]
Ortam değişkenleri için hemen hemen servis sağlayıcının desteği olur. Netlify da destekliyor. Eğer ayarlama yetkiniz yoksa, benimle özel olarak paylaşırsanız gerekli ayarlamaları yapabilirim :)

**Comment by yunusemredilber** [comment]
ENV ayarlamalarından sonra bu sorun çözüldü.
