### ISSUE TITLE
Chakra Theme oluşturulacak

### ISSUE THREAD

**Issue by ssukru** [pauieeecs/logicl#9]
Her şeyin birbiriyle orantılı ve tutarlı olması için tema oluşturalım. Dark Mode'u da böylece ekleyebiliriz.

**Comment by yunusemredilber** [comment]
Design system ve componentleri oluştururken [storybook](https://storybook.js.org/) kullanmanızı öneririm. İşlerinizi oldukça kolaylaştıracaktır. Aynı zamanda frontend için elimizde dinamik bir doküman olmuş olur.

**Comment by yunusemredilber** [comment]
Tip olarak da [https://theme-ui-styleguide.netlify.app/](https://theme-ui-styleguide.netlify.app/) gibi bir doküman oluşturulabilir.

**Comment by ssukru** [comment]
süper, inceliyorum :D
